public enum InputActionId {
    None = 0,
    Cancel = 1,
    Confirm = 2,
    ToggleRoleAttrPanel = 3,
    ToggleDebugUI = 4,
    NextStage = 5,
    AddHP = 6,
    ReduceHP = 7,
    AddMP = 8,
    ReduceMP = 9,
    MoveHorizontal = 10,
    MoveVertical = 11,
    MouseLeft = 12,
    MouseRight = 13,
    MouseX = 14,
    MouseY = 15,
    MouseScroll = 16,
}
